### ISSUE TITLE
Invalid type Error

### ISSUE THREAD

**Issue by shabeer-ali-m** [paulmillr/micro-eth-signer#4]
/node_modules/micro-eth-signer/index.js:63
            throw new TypeError('Invalid type');

Node v15.14.0
OS : Big Sur (Mac)

**Comment by paulmillr** [comment]
you need to report issues with more details

**Comment by shabeer-ali-m** [comment]
Your example.js is not working. Getting following error.

```sh
git clone https://github.com/paulmillr/micro-eth-signer.git
cd micro-eth-signer
npm i
node test/example.js
```
Error:
```
$ node test/example.js
/micro-eth-signer/index.js:63
            throw new TypeError('Invalid type');
                  ^

TypeError: Invalid type
    at normalizeField (/Users/shabeer/sites/creative/micro-eth-signer/index.js:63:19)
    at rawToSerialized (/Users/shabeer/sites/creative/micro-eth-signer/index.js:83:26)
    at new Transaction (/Users/shabeer/sites/creative/micro-eth-signer/index.js:146:20)
    at /Users/shabeer/sites/creative/micro-eth-signer/test/example.js:4:14
    at Object.<anonymous> (/Users/shabeer/sites/creative/micro-eth-signer/test/example.js:22:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

Let me know if you need any other information.

**Comment by paulmillr** [comment]
Thanks, working on this

**Comment by paulmillr** [comment]
Fixed

**Comment by shabeer-ali-m** [comment]
@paulmillr  Thanks
